In [1]:
import numpy as np

In [2]:
# A의 매트릭스 / b의 열벡터
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
b = np.matrix('15;19;26;44')
b

matrix([[15],
        [19],
        [26],
        [44]])

In [3]:
# A의 역행렬 여부 파악 
np.linalg.det(A)

853.9999999999995

In [4]:
# A의 대각행렬의 원소 출력
np.diag(A)

array([1, 5, 2, 3])

In [5]:
# 도출된 대각행렬의 원소를 다시 행렬로 표현하고 D에 할당 
# 따라서 D는 A의 대각행렬
D = np.diag(np.diag(A))
D

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [6]:
# A 행렬에서 - A의 대각행렬 빼서 "A의 상하삼각행렬을 구하기"
# R은 A의 상하삼각행렬 
R = A - D 
R

matrix([[0, 4, 2, 0],
        [9, 0, 0, 0],
        [4, 0, 0, 4],
        [6, 1, 8, 0]])

In [7]:
# D(A의 대각행렬)의 역행렬 파악 
np.linalg.det(D)

29.99999999999999

In [8]:
# D의 역행렬 구하기 
D_inv = np.linalg.inv(D)
D_inv

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.2       , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.        , 0.33333333]])

In [21]:
Maxlter = 1000
x0 = np.array([1,1,1,1])

for i in range(Maxlter):
    x1 = np.dot( D_inv, ( b - np.dot( R, x0) ) )
    x0 = x1
print(x0)

[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
