In [1]:
import numpy as np

# numpy의 행렬 

1. np.matrix : 수학적 연산이 필요할 때

2. np.array : 머신러닝에서 사용함 

### matrix 생성해보자 

In [2]:
A = np.matrix('1,2,3,4 ; 5,6,7,8; 9,10,11,12')
x = np.matrix('1;2;3;4') #vector
print(A)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


### array를 만들자

In [6]:
C = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
x = np.array([
    [1],
    [2],
    [3],
    [4]
])
print(C)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


## 행렬 곱셈 (=내적)
- 행렬의 덧셈은 볼 게 없어서 넘어가고 

### 행렬 / 벡터 곱 1 - 1

- 직접 수기로 계산하기 

$$
    \begin[bmatrix]
            1 & 4 & 2 & 0 \\
            9 & 5 & 0 & 0 \\
            4 & 0 & 2 & 4 \\
            6 & 1 & 8 & 3 \\
    \end[bmatrix]
$$

In [15]:
print(1*1 + 4*2 + 2*3 + 0*4)
print(9*1 + 5*2 + 0*3 + 0*4)
print(4*1 + 0*2 + 2*3 + 4*4)
print(6*1 + 1*2 + 8*3 + 3*4)

15
19
26
44


### 행렬 / 벡터 곱 1 - 2

- 직접 수기로 계산하기 

$$
    \begin[bmatrix]
            4 & 5 & 2 & 1 \\
            2 & 3 & 8 & 0 \\
            1 & 0 & 7 & 2 \\
    \end[bmatrix]
    \begin[bmatrix]
            1 \\
            2 \\
            3 \\
            4 \\
    \end[bmatrix]
$$

In [21]:
print(1*4 + 2*5 + 3*2 + 4*1)
print(1*2 + 2*3 + 3*8 + 4*0)
print(1*1 + 2*0 + 3*7 + 4*2)
print('첫번째 매트릭스에 4번째 행이 없기 때문에 계산이 되지 않음.')

24
32
30
첫번째 매트릭스에 4번째 행이 없기 때문에 계산이 되지 않음.


### 행렬/벡터 곱 - 두번째 

In [3]:
A = np.matrix('1,4,2,0; 9,5,0,0; 4,0,2,4; 6,1,8,3')
x = np.matrix('1;2;3;4')
b = np.zeros((4,1)) # 2차원 배열(열벡터)
n = 4

# to do matrix를 이용한 행렬곱의 결과를 출력
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        #열벡터는 2차원 배열이기 때문에 x와 y의 좌표를 꼭 적어줘야함
        val += A[i,j]*x[j,0]
    b[i] = val 
print(b)

[[15.]
 [19.]
 [26.]
 [44.]]


In [77]:
# 위 식이 그대로 가져 온 것 
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0]) # 1차원 배열 
n=4 

for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[15 19 26 44]


###### 오답노트 
- x[j]가 아닌 x[i]로 했는데 왜 틀렸는지 직접 계산해보기 


for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += A[i,j] * x[i,0]
        
= A00 * x0 + A01 * x0 + A02 * x0 + A03 * x0 
- 2차원 열벡터 x 값을 차례대로 곱하는 것이 아닌 첫번째 인덱스 x00에 고정되어 계산된 것을 볼 수 있다. 

- 따라서 for loop의 i 가 아닌 for loop의 j로 해야지 계산할 때마다 x00 x01 x02 x03으로 인덱싱되면서 할당되는 A값을 빠르게 대응해서 matrix 계산을 할 수 있음

### 행렬/벡터 곱 - 세번째

In [81]:
#In case matrix type 
A = np.matrix('1,4,2,0; 9,5,0,0; 6,1,8,3')
x = np.matrix('1;2;3;4')

print(A)
print('')
print(x)

b = A * x
print('')
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [6 1 8 3]]

[[1]
 [2]
 [3]
 [4]]

[[15]
 [19]
 [44]]


In [84]:
# In case array type (Wrong Case)
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])

print(A)
print('')
print(x)

b = A * x
print('')
print(b)

#행렬의 합을 구하듯 계산하기 때문에 array type은 이런식으로 계산하면 안됨

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]

[1 2 3 4]

[[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]


In [87]:
# In case array type (Right Case)
# Array type 행렬 계산시 np.dot() 혹은 np.matmul()로 계산해야한다
A = np.array([
    [1,4,2,0],
    [9,5,0,0],
    [4,0,2,4],
    [6,1,8,3]
])
x = np.array([1,2,3,4])

print(A)
print('')
print(x)

b = np.dot(A, x)
print('')
print(b)

b = np.matmul(A, x)
print('')
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]

[1 2 3 4]

[15 19 26 44]

[15 19 26 44]


### 실습. 행렬/벡터 곱의 array와 matrix의 계산차이를 알아보자 

In [156]:
A = np.matrix('4,5,2,1; 2,3,8,0; 1,0,7,2')
x = np.matrix('1;2;3;4')

In [157]:
print(A)
x

[[4 5 2 1]
 [2 3 8 0]
 [1 0 7 2]]


matrix([[1],
        [2],
        [3],
        [4]])

In [146]:
#for loop를 이용한 행렬/벡터 곱 구현
b = np.zeros((3,1))
for i in range(0,3):
    value = 0
    for j in range(0,3+1):
        value += A[i,j]*x[j,0]
    b[i] = value
print(b)

[[24.]
 [32.]
 [30.]]


In [124]:
#matrix type의 행렬/벡터 곱 구현
A*x

matrix([[24],
        [32],
        [30]])

In [152]:
A = np.array([[4,5,2,1], [2,3,8,0], [1,0,7,2]])
x = np.array([1,2,3,4])

In [154]:
print(A)
x

[[4 5 2 1]
 [2 3 8 0]
 [1 0 7 2]]


array([1, 2, 3, 4])

In [165]:
#for loop를 이용한 행렬/벡터 곱 구현

# b가 실수 타입이기 때문에 
b = np.zeros((3)) #만약 정수타입으로 바꾸고 싶으면 ,dtype = 'i' 해야됨
print(b.dtype)
for i in range(3):
    value = 0.0 # value값을 0.0 실수로 맞춰줘야함
    for j in range(3+1):
        value += A[i,j]*x[j]
    b[i] = value
print(b)

float64
[24. 32. 30.]


dtype('float64')

In [127]:
#matrix type의 행렬/벡터 곱 구현
Answer = np.dot(A, x)
print("np.dot type: ", Answer)

Answer2 = np.matmul(A, x)
print("np.matmul: ", Answer2)

np.dot type:  [24 32 30]
np.matmul:  [24 32 30]
