In [1]:
import numpy as np

#### 행렬과 벡터의 곱 확인 
- 내적으로 제외한 행렬/벡터 연산은
- 행렬/벡터의 모든 원소에 대한 반복적인 연산(+ - * /)
- 행렬/벡터끼리 연산을 하는 경우에 대해서 두 피연산자의 크기가 같아야 연산이 이뤄진다.

#### 스칼라와 벡터의 연산 

- 크기가 다른 피연산자의 연산인 경우
- 크기가 작은 피연산자를 반복 확장하여 크기가 큰 피연산자의 크기를 맞춘 후에 연산을 적용

In [23]:
np.random.seed(10)
vector = np.random.randint(10, size=6)
print(vector)

print(10*vector) # 브로드 캐스팅


#scalar Vector의 역할 #행 열 #할당할 숫자 
scalarVector = np.full((6,), 10)
print(scalarVector)
print(scalarVector * vector)

[9 4 0 1 9 0]
[90 40  0 10 90  0]
[10 10 10 10 10 10]
[90 40  0 10 90  0]


In [24]:
print(vector)
print(10 * vector)
print(10 + vector)
print(10 - vector)

[9 4 0 1 9 0]
[90 40  0 10 90  0]
[19 14 10 11 19 10]
[ 1  6 10  9  1 10]


####  스칼라와 행렬의 연산
- 벡터와 마찬가지, 자동으로 확장하여 모든 행렬내의 모든 원소에 반복적으로 적용 

In [29]:
arr = np.random.randint(10, size=(4,3))
arr

array([[8, 9, 0],
       [8, 6, 4],
       [3, 0, 4],
       [6, 8, 1]])

In [34]:
print(arr)
print(10 * arr)
print(10 - arr)
print(10 + arr)

[[8 9 0]
 [8 6 4]
 [3 0 4]
 [6 8 1]]
[[80 90  0]
 [80 60 40]
 [30  0 40]
 [60 80 10]]
[[ 2  1 10]
 [ 2  4  6]
 [ 7 10  6]
 [ 4  2  9]]
[[18 19 10]
 [18 16 14]
 [13 10 14]
 [16 18 11]]


#### 벡터와 벡터간의 연산

In [49]:
# 동일한 크기라면 문제가 일어나지 않는다. 
# 결과는 벡터의 크기와 동일하게 나타남
v1 = np.random.randint(10, size=4) 
v2 = np.random.randint(10, size=4)
print(v1)
print(v2)
print(v1 + v2)
print(v1 * v2)
#print(v1 / v2)
print(v1 - v2)

[8 8 6 6]
[5 6 0 0]
[13 14  6  6]
[40 48  0  0]
[3 2 6 6]


In [50]:
# 내적을 구한다면 스칼라가 출력됨
# 즉 벡터와 벡터간의 내적은 스칼라 형태의 결과가 나타난다.
np.dot(v1, v2)

88

In [51]:
# 크기가 다를 경우 문제가 발생 
v1 = np.random.randint(1, 10, size=(3,)) 
v2 = np.random.randint(1, 10, size=(4,))
print(v1+v2)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [53]:
# 자동으로 브로드캐스팅 되지 않음
np.dot(v1, v2)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

### inner / dot product
- 앞의 열과 뒤 행의 갯수가 같아야 해요 

In [56]:
arr1 = np.matrix('1,2,3,4')
arr2 = np.matrix('1;2;3;4')
print(arr1)
print(arr2)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [58]:
arr1 * arr2 #dot product = print Scalar 

matrix([[30]])

In [60]:
arr2 * arr1

matrix([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]])

In [64]:
arr3 = np.array([1,2,3,4])
arr4 = np.array([1,2,3,4])

In [65]:
np.dot(arr3, arr4)

30

In [67]:
np.matmul(arr4, arr3)

30

In [94]:
arr1.reshpae(4,1)

AttributeError: 'matrix' object has no attribute 'reshpae'

In [100]:
# 자동적으로 브로드캐스팅 되지 않기 때문에 
# 강제적으로 형태를 변형시켜서 곱해줘야됨;; 

print(arr1.reshape(4,1))
print(arr2.reshape(1,4))

np.dot(arr1.reshape(4,1), arr2.reshape(1,4))

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


matrix([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]])

#### 벡터와 행렬간의 연산
- 벡터는 행렬의 열크기에 맞춰야 계산이 진행된다 

In [118]:
np.random.seed(1)
arr1 = np.random.randint(1, 10, size=(4,))
arr2 = np.random.randint(1, 10, size=(3,4))
print(arr1)
print(arr2)

[6 9 6 1]
[[1 2 8 7]
 [3 5 6 3]
 [5 3 5 8]]


In [119]:
# 벡터가 행렬의 크기에 맞춰 자동으로 확장(브로드 캐스팅)
# 
print(arr1 + arr2 )
print(arr1 * arr2 )

[[ 7 11 14  8]
 [ 9 14 12  4]
 [11 12 11  9]]
[[ 6 18 48  7]
 [18 45 36  3]
 [30 27 30  8]]


In [116]:
np.random.seed(1)
arr1 = np.random.randint(1, 10, size=(4,))
arr2 = np.random.randint(1, 10, size=(4,3))
print(arr1)
print(arr2)

[6 9 6 1]
[[1 2 8]
 [7 3 5]
 [6 3 5]
 [3 5 8]]


In [117]:
# 벡터가 행렬의 크기에 맞춰 자동으로 확장(브로드 캐스팅)
# 
print(arr1 + arr2 )
print(arr1 * arr2 )

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

#### 행렬과 행렬간의 연산
- 행과 열의 갯수가 반드시 일치해야 계산이 진행된다. 
- 2차원 행렬과 3차원 행렬간에도 역시 브로드 캐스팅이 적용됨 
- 행렬의 차원이 다르면 브로드 캐스팅 역시 적용이 된다.
- 자동으로 확장되었을 경우 모양이 일치하기만 하면 된다. 

In [121]:
np.random.seed(1)
arr1 = np.random.randint(1, 10, size=(2,3))
arr2 = np.random.randint(1, 10, size=(2,3))

In [122]:
print(arr1)
print(arr2)

[[6 9 6]
 [1 1 2]]
[[8 7 3]
 [5 6 3]]


In [124]:
print(arr1 + arr2)
print(arr1 * arr2)

[[14 16  9]
 [ 6  7  5]]
[[48 63 18]
 [ 5  6  6]]


디멘션이 다를경우 
낮은 차원의 행렬이 높은 차원의 행렬에 맞춰 자동으로 브로드캐스팅됨