In [2]:
# nd.array하지 않고 array만 써도 배열을 불러오는 방법 중 하나
#from numpy import *\
#하지만 나중에 쓸거니
import numpy as np

In [3]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

# ndarray 데이터 생성하기(Random)
- ones, zeros, empty, full, linspace 외의 데이터를 생성하기 
- random module의 함수를 통해 ndarray를 생성해보기 

#### rand: 0~1 사이의 랜덤한 ndarray를 생성하기 

In [7]:
np.random.rand(5, )

array([0.28254478, 0.11125493, 0.06755619, 0.7042472 , 0.37210769])

In [70]:
#다차원도 쌉가능이지 
np.random.rand(4,3)

array([[0.42665534, 0.75808144, 0.45707601],
       [0.60643921, 0.92234252, 0.26141857],
       [0.6237619 , 0.17382971, 0.88102534],
       [0.93344512, 0.6921897 , 0.8270809 ]])

### randn(random normal distribution) 함수 
- 정규분포 (가우스 분포)
- 정규분포로 샘플링된 랜덤한 데이터를 생성 
- 통계학에서 중요하게 사용하는 분포
- 좋은 모델을 만들려면 훌륭한 표본이 있어야 하고 이는 샘플링을 훌륭하게 해야한다

In [71]:
np.random.randn(5)

array([ 2.38433401, -1.03849823,  1.37403011,  0.4630746 ,  0.29478269])

In [72]:
np.random.randn(4,3)

array([[ 1.08206923,  0.77908037, -0.54173134],
       [-2.49030775,  0.82929967,  0.52915517],
       [-1.01683238, -2.12044401,  0.81083351],
       [ 0.99695848, -0.28424901,  0.49260882]])

### randint
- 지정된 정수 사이에서 랜덤한 ndarray를 생성
- 차원을 생성하고 싶으면 ,size=(행, 렬) 코드 추가

In [18]:
np.random.randint(1, 10)

8

In [27]:
np.random.randint(1, 10, size=(5))

array([3, 6, 7, 1, 6])

In [73]:
np.random.seed(13`)
np.random.randint(1, 10, size=(5,8))

array([[3, 1, 1, 7, 3, 5, 4, 5],
       [3, 7, 6, 5, 3, 1, 4, 6],
       [4, 7, 6, 2, 3, 9, 9, 7],
       [3, 5, 6, 8, 4, 6, 9, 4],
       [9, 6, 2, 9, 2, 8, 8, 6]])

### choice 
- 주어진 정수나, 1차원의 ndarray로부터 랜덤하게 샘플링하여 ndarray를 생성하는 함수

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#np.arange(10)한 ndarray로부터 랜덤하게 샘플링(초이스)
np.random.choice(10, size = (4,3))

array([[5, 6, 3],
       [5, 4, 5],
       [9, 5, 0],
       [1, 8, 2]])

In [85]:
#위의 코드를 자세하게 설명
x = np.arange(10)
np.random.choice(x, size=(4,3))

# 즉 x의 값은 np.arange(x)를 축약한 것으로 인지하면 됨

array([[3, 2, 0],
       [6, 1, 7],
       [2, 4, 1],
       [5, 9, 4]])

### 확률분포에 따른 ndarray 생성
- 유명한 분포: 정규, 포아송, 베타분포, ... 
- 수집된 데이터로부터 확률분포를 구할 수 있다. 

In [114]:
#시작과 끝을 지정하는 정규 분포
                #시작  #끝  #차원   
np.random.uniform(1.0, 3.0, size=(4,3))

array([[1.51495085, 2.82716346, 1.91569902],
       [1.26042358, 2.61978333, 1.80693968],
       [1.04886529, 2.71366209, 1.54858964],
       [2.41821193, 1.71154469, 2.58861812]])

In [88]:
#정규 분포
np.random.normal(size=(4,3))

array([[ 0.16951686,  1.4997959 ,  0.70848184],
       [ 0.83303883, -0.29892548, -2.24797567],
       [-0.54669855,  0.19365196, -0.60778756],
       [-0.93825855, -0.62765454,  0.44554792]])

In [90]:
#이것도 정규 분포
np.random.rand(4,3)

array([[0.052298  , 0.43538852, 0.33765272],
       [0.58220134, 0.33390127, 0.35013409],
       [0.85945354, 0.09487886, 0.81867458],
       [0.2201809 , 0.45593114, 0.9684687 ]])

### seed
- 랜덤 데이터 생성의 기준
- 시드값이 한 번 지정되면 랜덤값은 그대로 고정됨 
- 한 번 값이 할당된 후에, 행렬의 크기가 바뀌더라도 할당됐던 좌표의 값은 그대로 고정됨

In [121]:
np.random.seed(10) #seed = fix?
np.random.randn(4,3)

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737]])

In [17]:
np.random.randn(4,3)

array([[ 0.75870086, -1.03285064, -0.06726514],
       [ 0.22687216, -3.7004789 , -0.44530956],
       [ 0.85654153,  1.1800043 , -1.24028834],
       [ 0.15743183,  0.36604957, -0.56275864]])

## 다차원을 1차원으로 바꾸는 것 (12/1 추가 설명)  
- np.ravel(객체)
- 객체.ravel() 
- 객체.flatten()

In [129]:
arr = np.random .randint(100, size=(4,3))
arr

array([[22, 23, 94],
       [11, 28, 74],
       [88,  9, 15],
       [18, 80, 71]])

In [137]:
np.ravel(arr)

array([22, 23, 94, 11, 28, 74, 88,  9, 15, 18, 80, 71])

In [133]:
# default값
# C : row 우선 변경 
np.ravel(arr, order='C')

array([22, 23, 94, 11, 28, 74, 88,  9, 15, 18, 80, 71])

In [136]:
# F : coulmn 우선 변경 
np.ravel(arr, order='F')

array([22, 11, 88, 18, 23, 28,  9, 80, 94, 74, 15, 71])

##### ravel()

In [126]:
arr.ravel()

array([30, 30, 89, 12, 65, 31, 57, 36, 27, 18, 93, 77])

In [134]:
arr.ravel(order='F')

array([22, 11, 88, 18, 23, 28,  9, 80, 94, 74, 15, 71])

##### flatten()

In [127]:
arr.flatten()

array([30, 30, 89, 12, 65, 31, 57, 36, 27, 18, 93, 77])

In [135]:
arr.flatten(order='F')

array([22, 11, 88, 18, 23, 28,  9, 80, 94, 74, 15, 71])