In [2]:
import numpy as np

### ndarray 기본 연산자 
- add 덧셈 
- subtract 뺄셈 
- multiply 곱셈 
- divide 나눗셈

In [12]:
np.random.seed(1)
x = np.random.randint(10, size=(4,3))
y = np.random.randint(10, size=(4,3))
print(x)
print('')
print(y)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]

[[5 2 4]
 [2 4 7]
 [7 9 1]
 [7 0 6]]


###### 행렬의 덧셈

In [16]:
#행렬의 덧셈
np.add(x,y)

array([[10, 10, 13],
       [ 7,  4,  7],
       [ 8, 16,  7],
       [16,  2, 10]])

In [17]:
x+y

array([[10, 10, 13],
       [ 7,  4,  7],
       [ 8, 16,  7],
       [16,  2, 10]])

###### 행렬의 뺄셈

In [18]:
np.subtract(x,y)

array([[ 0,  6,  5],
       [ 3, -4, -7],
       [-6, -2,  5],
       [ 2,  2, -2]])

In [19]:
x-y

array([[ 0,  6,  5],
       [ 3, -4, -7],
       [-6, -2,  5],
       [ 2,  2, -2]])

###### 행렬의 나눗셈
- nan이나 inf가 나오는 것은 원소에 0이 포함되어 있기 때문

In [14]:
#행렬의 나눗셈
np.divide(x, y)

<ipython-input-14-c34c26bd317a>:2: RuntimeWarning: invalid value encountered in true_divide
  np.divide(x, y)


array([[1.        , 2.5       , 2.        ],
       [1.25      , 1.2       , 0.8       ],
       [2.        , 2.        , 0.88888889],
       [0.33333333,        nan, 2.        ]])

In [23]:
x/y

<ipython-input-23-a2dd4ac70d63>:1: RuntimeWarning: invalid value encountered in true_divide
  x/y


array([[1.        , 2.5       , 2.        ],
       [1.25      , 1.2       , 0.8       ],
       [2.        , 2.        , 0.88888889],
       [0.33333333,        nan, 2.        ]])

###### 행렬의 곱셈
- 절대로 일반적인 행렬의 곱셈식이 아니다!
- 같은 좌표에 있는 X행렬과 Y행렬의 원소 x와 y를 곱한 것일 뿐이다! 

In [20]:
#행렬 곱셈 아님 x와 y의 같은 좌표의 원소끼리 곱한 것일 뿐
np.multiply(x,y)

array([[25, 16, 36],
       [10,  0,  0],
       [ 7, 63,  6],
       [63,  0, 24]])

In [21]:
#행렬 곱셈 아님 x와 y의 같은 좌표의 원소끼리 곱한 것일 뿐
x * y

array([[25, 16, 36],
       [10,  0,  0],
       [ 7, 63,  6],
       [63,  0, 24]])

### ndarray 통계 함수
- 평균, 분산, 중앙, 최대, 최소, 표준분산 ...
- axis(축)에 대한 이해

In [5]:
print(x)

[[9 1 5]
 [3 3 2]
 [6 0 7]
 [6 5 2]]


In [13]:
arr = x.flatten()
arr.sort
print(arr)

[9 1 5 3 3 2 6 0 7 6 5 2]


###### 평균 mean

In [25]:
np.mean(x)

4.25

In [26]:
x.mean()

4.25

###### 최대 max

In [22]:
np.max(x)

9

In [23]:
x.max()

9

###### 최소 min

In [28]:
np.min(x)

0

In [43]:
x.min()

0

###### 분산 var

In [29]:
np.var(x)

5.854166666666667

In [44]:
x.var()

5.854166666666667

###### 중앙값 median 
- 원소들을 정렬했을 때, 중앙에 오는 값을 중앙값이라고 함 

In [24]:
np.median(x)

5.0

###### 표준분산 std

In [25]:
np.std(x)

3.1710495984067415

### ndarray 집계(aggregation)함수
- 합(sum), 누적합(cumsum)

In [26]:
print(x)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]


In [27]:
np.sum(x)

56

In [28]:
np.cumsum(x)

array([ 5, 13, 22, 27, 27, 27, 28, 35, 41, 50, 52, 56], dtype=int32)

### any, all 함수 
- any: 특정 조건을 만족하는 값이 하나라도 있으면 True 
- all: 모든 원소가 조건을 만족하면 True

In [29]:
print(x)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]


In [51]:
x > 5

array([[False, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False, False, False]])

In [52]:
np.any(x >5)

True

In [53]:
np.all(x > 5)

False

In [55]:
np.all( x>= 0)

True

### where 함수 
- 조건에 따라 참인 값만 선택
- 조건에 맞지 않는 경우 인자의 값을 사용

In [30]:
print(x)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]


In [31]:
# x가 5보다 큰 경우인(6,7,8) 참인 값만 선택되고 조건에 맞는 거짓인 값(0,1,2,3,4,5)은 0으로 출력
np.where(x > 5, x, 0)

array([[0, 8, 9],
       [0, 0, 0],
       [0, 7, 6],
       [9, 0, 0]])

 #### axis(축): x축, y축 
- 함수의 인자로 axis를 인자로 갖는 함수들이 존재
- 2차원 배열에서는 행, 열로 확인하면 된다.
- 아래의 함수들 을 이용해 확인해보자

##### 1차원 배열의 경우

In [88]:
arr = np.random.randint(10, size=(5,))
print(arr)

[3 4 6 5 4]


In [72]:
arr.sum()

20

In [73]:
arr.sum(axis=0)

20

In [75]:
#1차원 배열이기 때문에 축이 하나 뿐이라 축을 2개 이상 삽입이 불가능함##### 1차원 배열의 경우
arr.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

##### 2차원 배열의 경우
- #axis = 0은 행
- #axis = 1은 열

In [115]:
np.random.seed(1)
arr = np.random.randint(10, size=(2, 3))
print(arr)
print(arr.shape)

[[5 8 9]
 [5 0 0]]
(2, 3)


In [116]:
arr.sum()

27

In [117]:
#axis = 0은 행
#행을 기준으로 모든 열의 값을 더해준다
arr.sum(axis=0)

array([10,  8,  9])

In [119]:
#axis = 1은 열
#열을 기준으로 모든 행의 값을 더해준다
arr.sum(axis=1)

array([22,  5])

mean도 적용해보자구 

In [129]:
np.random.seed(1)
a = np.random.randint(10, size=(3,3))
a

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [130]:
a.mean()

4.555555555555555

In [136]:
#axis = 1 행을 기준으로 3개 열의 평균
a.mean(axis=0)

array([3.66666667, 5.        , 5.        ])

In [133]:
#axis = 1 열을 기준으로 3개 행의 평균
a.mean(axis=1)

array([7.33333333, 1.66666667, 4.66666667])