# Series타입 
- Data Frame 타입 
- 

In [1]:
import numpy as np
import pandas as pd 

In [78]:
# 넘파이를 기반으로 데이터를 인덱싱하는 부분이 가미된 판다스 
series1 = pd.Series([1,2,3])
series1
#인덱스 # 데이터

0    1
1    2
2    3
dtype: int64

In [79]:
#직접 인덱싱도 할 수 있다.
                    #데이터  #인덱스     
series2 = pd.Series([1,2,3], [100,200,300])
series2

100    1
200    2
300    3
dtype: int64

In [9]:
series2.index

Int64Index([100, 200, 300], dtype='int64')

In [11]:
series2.values

array([1, 2, 3], dtype=int64)

In [13]:
series3 = pd.Series([1,2,3], ['a', 'b', 'c'])
series3

a    1
b    2
c    3
dtype: int64

In [14]:
series3.index

Index(['a', 'b', 'c'], dtype='object')

In [16]:
series3.values

array([1, 2, 3], dtype=int64)

In [19]:
print(series3['c'])
print(series2[200])
print(series1[1])

3
2
2


In [29]:
# numpy의 슬라이싱도 역할한다. 
print(series3['b':])
print(series2[1:])

b    2
c    3
dtype: int64
200    2
300    3
dtype: int64


파이썬의 딕셔너리와 같다고 생각하면 됨 

## Series의 여러가지 속성

In [33]:
sample = pd.Series([1,1,2,1,2,2,2,1,1,3,3,4,5,5,7,np.NaN], dtype='f')
sample

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float32

In [34]:
len(sample)

16

In [36]:
# len 뿐만 아니라 size속성도 있음
sample.size

16

In [37]:
sample.shape

(16,)

In [43]:
# 몇 차원인지 알려주는 함수
sample.ndim

1

In [40]:
# 중복
sample.unique()

array([ 1.,  2.,  3.,  4.,  5.,  7., nan], dtype=float32)

In [42]:
# 갯수 NaN은 세지 않음 
sample.count()

15

In [44]:
# NaN을 제외한 평균
sample.mean()

2.6666667461395264

In [47]:
# 중복값의 빈도 수 역시 NaN은 카운트하지 않음 
sample.value_counts()

1.0    5
2.0    4
5.0    2
3.0    2
7.0    1
4.0    1
dtype: int64

In [67]:
# 원소의 직접인덱싱
print(type(sample[2]))
print(sample[2])
# 원소의 2차원 인덱싱
print(type(sample[[2]]))
print(sample[[2]])

<class 'numpy.float32'>
2.0
<class 'pandas.core.series.Series'>
2    2.0
dtype: float32


In [68]:
# 멀티 인덱싱
# 넘파이의 행렬 인덱싱가는 다른 표현 
sample[[1,2,3,4]]

1    1.0
2    2.0
3    1.0
4    2.0
dtype: float32

In [69]:
# 실수표현이 판다스 타입이기 때문에 메서드가 제대로 먹힘 
sample[[1,2,3,4]].value_counts()

2.0    2
1.0    2
dtype: int64

In [65]:
# 넘파이의 실수표현(스칼라)이기 떄문에 판다스 메서드가 통하지 않음 위 3행 확인해보기 
sample[2].value_counts()

AttributeError: 'numpy.float32' object has no attribute 'value_counts'

In [72]:
# 앞에 수 (디폴트 5개)
sample.head()

0    1.0
1    1.0
2    2.0
3    1.0
4    2.0
dtype: float32

In [73]:
            #갯수 지정
sample.head(n=8)

0    1.0
1    1.0
2    2.0
3    1.0
4    2.0
5    2.0
6    2.0
7    1.0
dtype: float32

In [75]:
# 끝에 몇 개 (디폴트 5개)
sample.tail()

11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float32

In [76]:
sample.tail(n=2)

14    7.0
15    NaN
dtype: float32

In [81]:
sample1 = pd.Series([1,2,3,4], ['a','b','c','d'])
sample2 = pd.Series([5,6,7,8], ['d','c','b','a'])

In [82]:
print(sample1 + sample2)  # 할당된 인덱스를 기준으로 할당됨 
print(sample1 * sample2)

a    9
b    9
c    9
d    9
dtype: int64
a     8
b    14
c    18
d    20
dtype: int64


In [83]:
sample1['e']= 10
sample2['f'] = 20 
print(sample1)
print(sample2)

a     1
b     2
c     3
d     4
e    10
dtype: int64
d     5
c     6
b     7
a     8
f    20
dtype: int64


In [86]:
# 서로의 샘플에 동일한 인덱스가 없다면 NaN으로 출력
print(sample1 + sample2)

a    9.0
b    9.0
c    9.0
d    9.0
e    NaN
f    NaN
dtype: float64


# fancy indexing(boolean indexing) 

In [96]:
series1[[True, False, True]]

0    1
2    3
dtype: int64

In [140]:
sample3 = pd.Series(np.arange(10), np.arange(10)+1)
sample3

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [116]:
np.arange(10+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
sample3[sample3 > 5]

7     6
8     7
9     8
10    9
dtype: int32

In [115]:
sample3[sample3 % 2 == 0]

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [117]:
sample3.index > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [118]:
sample3[sample3.index>5]

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [124]:
sample3[(sample3 > 5) & (sample3 < 8 )]

7    6
8    7
dtype: int32

In [131]:
sample3 >= 7

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
dtype: bool

In [125]:
(sample3 >= 7)

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
dtype: bool

In [132]:
# 결측치에 대한 통계를 알고 싶을때
# NaN의 값에 대한 통계를 알고 싶을 때
# 어떤 조건의 참인 결과의 갯수 
(sample3 >= 7).sum()

3

In [130]:
(sample3[sample3 >= 7])

8     7
9     8
10    9
dtype: int32

In [129]:
(sample3[sample3 >= 7]).sum()

24

# DROP & Slice 

In [167]:
sample3 = pd.Series(np.arange(10), np.arange(10)+1)

In [165]:
# 원하는 요소를 드랍해보기 
                 # inplace= True주어진 시리즈 내에서 바로 드랍해버리기 
            #인덱스 
sample3.drop(6, inplace=True)

In [156]:
sample3.drop(8)

1     0
2     1
3     2
4     3
5     4
6     5
7     6
9     8
10    9
dtype: int32

In [166]:
sample3[0:10]
# 8번 인덱스를 드랍했지만 다시 돌아왔음
# 6번 인덱스를 인플레이스 드랍하니 진짜 죽어버렸음 

1     0
2     1
3     2
4     3
5     4
7     6
8     7
9     8
10    9
dtype: int32